name: Refresh iCloud Calendar

on:
  schedule:
    - cron: '0 */12 * * *'    # every 4 hours; adjust as you like
  workflow_dispatch:        # also allows manual trigger

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download latest .ics
        run: |
          curl -L 'https://p28-caldav.icloud.com/published/2/MTk5MTY1Mjg0MTk5MTY1Mn36jlThhyne4huQCwOymWWDNlC-pFdjiVMB-Vz4dy-Cyq_QN8C-WjZU7FRM_0EwrlZMnPOFL3alE2uV1r8vDvY' \
            -o calendar.ics

      - name: Commit & push changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add calendar.ics
          # Only commit if there are changes
          if ! git diff --cached --exit-code; then
            git commit -m "Automated: update calendar.ics"
            git push
          else
            echo "No changes to calendar.ics"
          fi